FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
COPY fraud/pom.xml fraud/pom.xml
COPY clients/pom.xml clients/pom.xml
RUN mvn dependency:go-offline -pl fraud -am -DskipTests || true
COPY . .
RUN mvn clean package -pl fraud -am -DskipTests

FROM eclipse-temurin:21-jre
COPY --from=build /app/fraud/target/fraud-1.0-SNAPSHOT.jar /app.jar
EXPOSE 8081
ENTRYPOINT ["java", "-jar", "/app.jar"]
