FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
COPY eureka-server/pom.xml eureka-server/pom.xml
RUN mvn dependency:go-offline -pl eureka-server -am -DskipTests || true
COPY . .
RUN mvn clean package -pl eureka-server -am -DskipTests

FROM eclipse-temurin:21-jre
COPY --from=build /app/eureka-server/target/eureka-server-1.0-SNAPSHOT.jar /app.jar
EXPOSE 8761
ENTRYPOINT ["java", "-jar", "/app.jar"]
