FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
COPY notification/pom.xml notification/pom.xml
COPY clients/pom.xml clients/pom.xml
RUN mvn dependency:go-offline -pl notification -am -DskipTests || true
COPY . .
RUN mvn clean package -pl notification -am -DskipTests

FROM eclipse-temurin:21-jre
COPY --from=build /app/notification/target/notification-1.0-SNAPSHOT.jar /app.jar
EXPOSE 8083
ENTRYPOINT ["java", "-jar", "/app.jar"]
