FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
COPY inventory/pom.xml inventory/pom.xml
RUN mvn dependency:go-offline -pl inventory -am -DskipTests || true
COPY . .
RUN mvn clean package -pl inventory -am -DskipTests

FROM eclipse-temurin:21-jre
COPY --from=build /app/inventory/target/inventory-1.0-SNAPSHOT.jar /app.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "/app.jar"]
