FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
COPY gateway/pom.xml gateway/pom.xml
RUN mvn dependency:go-offline -pl gateway -am -DskipTests || true
COPY . .
RUN mvn clean package -pl gateway -am -DskipTests

FROM eclipse-temurin:21-jre
COPY --from=build /app/gateway/target/gateway-1.0-SNAPSHOT.jar /app.jar
EXPOSE 8765
ENTRYPOINT ["java", "-jar", "/app.jar"]
